---
install:
  - cpanm --quiet  --notest --skip-satisfied Class::Tiny Config::AutoConf Module::Pluggable::Object Carp
  - cpanm --quiet --installdeps --notest .
language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
