---
install:
  - cpanm --notest --skip-satisfied Test::WriteVariants Config::AutoConf Carp App::mymeta_requires ExtUtils::BundleMaker
  - perl Makefile.PL
  - make manifest
  - mymeta-requires --runtime --build --test --configure --develop --recommends --suggests | cpanm
language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
